ktor:
    application:
        modules:
            - com.arx.ApplicationKt
    deployment:
        port: 9090
        host: 0.0.0.0
    cors:
      allowedOrigins:
        - "localhost:9090"
        - "127.0.0.1:9090"
      allowedMethods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
      allowedHeaders:
        - "Content-Type"
        - "Authorization"

mongo:
  uri: "mongodb://localhost:27017"
  database: "cricket_db"
